config/routes.rb
Rails.application.routes.draw do
  resources :projects
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all
  end

  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monstera</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!-- ensure this is using pack_tag rather than link_tag -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@300;400;600&display=swap" rel="stylesheet">
</head>

  <body class="font-sans">
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Egg</h1>

app/views/pages/home.html.erb
<section class="bg-primary flex pt-40 pb-12 h-full w-full">
  <div class="container">
    <div class="w-1/2">
      <h1 class="text-black font-bold uppercase leading-tight text-8xl">
        Digital<br>
        Agency
      </h1>
    </div>
  </div>
</section>

<section class="bg-primary flex py-24 md:pt-20 h-full w-full">
  <div class="container">
    <div class="max-w-3xl">
      <h2 class="text-2xl md:text-3xl text-black leading-tight font-bold mb-4">
      Who are we?
      </h2>
    </div>
    <div class="mt-3">
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsam quod quidem obcaecati sunt reiciendis nihil ipsum aliquam magnam, maiores tempora omnis tenetur odit cumque quos temporibus, quae amet aliquid.</p>
    </div> 
  </div>
</section>

<% if @projects.present? %>
  <section class="bg-secondary py-12 md:py-20 w-full">
    <div class="container max-w-screen-lg">
      <h2 class="text-2xl md:text-3xl text-center text-white leading-tight font-bold mb-8">Selected Work</h2>
      <div class="grid grid-cols-3 gap-6">
        <% @projects.each do |project| %>
          <%= link_to project do %>
            <div class="bg-primary rounded-lg py-6 px-4 ">
              <h2 class="text-xl md:text-2xl leading-tight mb-4"><%= project.title %></h2>
              <p class=""><%= project.description %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
<% end %>

<section class="bg-primary py-12 md:py-20">
  <div class="container max-w-screen-lg">
    <div class="text-center mx-auto mb-8 lg:mb-16">
      <h2 class="text-2xl md:text-3xl text-black leading-tight font-bold mb-4">
        Our Recent Clients
      </h2>
    </div>
    <div class="grid grid-cols-3 md:grid-cols-5 gap-8 md:gap-16">
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
      <div class="col-span-1">
        <%= image_pack_tag "gardening.png" %>
      </div>
    </div>
  </div>
</section>

<section class="bg-secondary flex justify-center items-center py-12 md:pt-20">
  <div class="container max-w-screen-lg">
    <div class="text-center mx-auto mb-8 lg:mb-16">
      <h2 class="text-2xl md:text-4xl uppercase text-white leading-tight font-bold mb-8">
        Start your project today
      </h2>
      <button class="bg-primary rounded-lg py-4 px-6">
        <%= link_to 'Get in touch', contact_path %>
      </button>
    </div>
    </div>
  </div>
</section>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/shared/_footer.html.erb
  <footer class="bg-secondary text-white pb-12">
    <div class="container flex items-center justify-center">
      <div class="px-10">
      <h2 class="text-center text-xl mb-8 uppercase">Monstera</h2>
      <ul class="flex items-center text-center">
        <li><a class="text-lg" href="#">Facebook</a></li>
        <li><a class="text-lg ml-8" href="#">Twitter</a></li>
        <li><a class="text-lg ml-8" href="#">Instagram</a></li>
      </ul>
      </div>
    </div>
  </footer>

app/views/shared/_header.html.erb
<header class="bg-primary w-full flex justify-between items-center">
  <h3 class="font-bold text-black uppercase py-6 pl-24">Monstera</h3>
  <ul class="flex items-center text-center pr-24">
    <li class="ml-8"><a href="/about">About</a></li>
    <li class="ml-8"><%= link_to 'Projects', projects_path %></li>
  </ul>
</header>